from fastapi import FastAPI
app = FastAPI()

@app.get("/")
def hello():
    return {"message" : "Hello, will take my understanding of fast api to advanced level"}


@app.get("/about")
def about_section():
    return "hey"

# while running the app, we use --reload at the end. that helps the changes made to automatically get reflected and so we don't have to restart the server again.

# also, an autogenerated interactive documentation is ready for all files created using fastapi. just add /docs after the url. eg: http://127.0.0.1:8000/docs 